version: '3'
services:
  github-action-sbt:
    build: .
    working_dir: /github/workspace
    command: aetherDeploy
    environment:
      INPUT_SBT_PROJECT_DIRECTORY: ./test
      INPUT_SETTINGS_SBT: |
        Compile := true
        externalResolvers += "GitHub lokkju Apache Maven Packages" at "https://maven.pkg.github.com/lokkju/github-action-sbt"
        publishTo := Some("GitHub lokkju Apache Maven Packages" at "https://maven.pkg.github.com/lokkju/github-action-sbt")
        credentials += Credentials("GitHub Package Registry", "maven.pkg.github.com", "lokkju", "${GITHUB_TOKEN}")
    volumes:
    - ./:/github/workspace
